/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.controlador_CP;
import static Vista.NOTAS.tbDatos;
import static Vista.NOTAS.txtcantidad;
import static Vista.NOTAS.txtclave;
import static Vista.NOTAS.txtdescripcion;
import static Vista.NOTAS.txtexistencia;
import static Vista.NOTAS.txtprecio;
import static Vista.NOTAS.txttotalproducto;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Oscar
 */
public class CP extends javax.swing.JInternalFrame {

    /**
     * Creates new form CP
     */
    public CP() {
        initComponents();
        cargar_estados();
        cargar_colonias("Puebla", "Tehuacan");
        
    }
    Controlador.controlador_CP CP=new controlador_CP();
    
    
    public void cargar_estados(){
       ResultSet rs= CP.consultar_estados_C();
       cmbestado.removeAllItems();
        try {
            while(rs.next()){
                cmbestado.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void cargar_municios(String estado){
       ResultSet rs= CP.consultar_Municipio_c(estado);
       cmbmunicipio.removeAllItems();
        try {
            while(rs.next()){
                cmbmunicipio.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void cargar_colonias(String estado,String municipios){
         DefaultTableModel rs= CP.cargar_tabla_cliente(estado, municipios);
         tbcolonias.setModel(rs);
                   TableColumnModel colummodel= tbcolonias.getColumnModel();
       colummodel.getColumn(0).setPreferredWidth(30);
        colummodel.getColumn(1).setPreferredWidth(30);
        colummodel.getColumn(2).setPreferredWidth(400);
        colummodel.getColumn(3).setPreferredWidth(20);
       
       
    } 
     void llenar_tabla(String estado,String mun) {
        
        ResultSet rs=CP.consultar_colonias(estado, mun);
        
        try {
            while(rs.next()){
        DefaultTableModel tabladet = (DefaultTableModel) tbcolonias.getModel();
        String[] registros = new String[8];
               
                
                String dias = rs.getString("colonia");
                String diaArray[] = dias.split(";");
                
                for (String dia : diaArray) {
                    
                    
                    
                    
                    registros[0] = rs.getString(4);
                    registros[1] = rs.getString(3);
                    registros[2] = dia;
                    registros[3] =  rs.getString(1);
                    tabladet.addRow(registros);
                         tbcolonias.setModel(tabladet);
   
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcolonias = new javax.swing.JTable();
        cmbestado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbmunicipio = new javax.swing.JComboBox<>();
        txtbuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        tbcolonias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ESTADO", "MUNICIPIO", "COLONIA", "CP"
            }
        ));
        tbcolonias.getTableHeader().setReorderingAllowed(false);
        tbcolonias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcoloniasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcolonias);

        cmbestado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbestadoFocusLost(evt);
            }
        });
        cmbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbestadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado");

        jLabel2.setText("Municipio");

        cmbmunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbmunicipioFocusLost(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        jLabel3.setText("BUSCAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(193, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("CODIGOS POSTALES", jPanel1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-shutdown-32.png"))); // NOI18N
        jMenu1.setText("SALIR");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestadoActionPerformed

    private void cmbestadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbestadoFocusLost
        cargar_municios(cmbestado.getSelectedItem().toString());


        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestadoFocusLost

    private void cmbmunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbmunicipioFocusLost

        cargar_colonias(cmbestado.getSelectedItem().toString(), cmbmunicipio.getSelectedItem().toString());


        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmunicipioFocusLost
 DefaultTableModel dm;
    private void filtro(String consulta, JTable jtableBuscar) {
        dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }
    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        filtro(txtbuscar.getText().toUpperCase(), tbcolonias);   // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void tbcoloniasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcoloniasMouseClicked
 int filasel = tbcolonias.getSelectedRow();
        String a = (String) tbcolonias.getValueAt(filasel, 3);
NOTAS.txtcp.setText(a);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_tbcoloniasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbestado;
    private javax.swing.JComboBox<String> cmbmunicipio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbcolonias;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
