/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.controlador_CP;

import Utilerias.CambiaPanel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowFilter;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author RojeruSan
 */
public class Pn_CP extends javax.swing.JPanel {
  
  
    /**
     * Creates new form pnlHome
     */
    public Pn_CP() {
        initComponents();
        RowApariencia();
        RowApariencia();

    cargar_estados();
        cargar_colonias("Puebla", "Tehuacan");
        //cargar_tabla("");

    }  Controlador.controlador_CP CP=new controlador_CP();
    
    
    public void cargar_estados(){
       ResultSet rs= CP.consultar_estados_C();
       cmbestado.removeAllItems();
        try {
            while(rs.next()){
                cmbestado.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void cargar_municios(String estado){
       ResultSet rs= CP.consultar_Municipio_c(estado);
       cmbmunicipio.removeAllItems();
        try {
            while(rs.next()){
                cmbmunicipio.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void cargar_colonias(String estado,String municipios){
         DefaultTableModel rs= CP.cargar_tabla_cliente(estado, municipios);
         tbDatos.setModel(rs);
                   TableColumnModel colummodel= tbDatos.getColumnModel();
       colummodel.getColumn(0).setPreferredWidth(30);
        colummodel.getColumn(1).setPreferredWidth(30);
        colummodel.getColumn(2).setPreferredWidth(400);
        colummodel.getColumn(3).setPreferredWidth(20);
       
       
    } 
     void llenar_tabla(String estado,String mun) {
        
        ResultSet rs=CP.consultar_colonias(estado, mun);
        
        try {
            while(rs.next()){
        DefaultTableModel tabladet = (DefaultTableModel) tbDatos.getModel();
        String[] registros = new String[8];
               
                
                String dias = rs.getString("colonia");
                String diaArray[] = dias.split(";");
                
                for (String dia : diaArray) {
                    
                    
                    
                    
                    registros[0] = rs.getString(4);
                    registros[1] = rs.getString(3);
                    registros[2] = dia;
                    registros[3] =  rs.getString(1);
                    tabladet.addRow(registros);
                         tbDatos.setModel(tabladet);
   
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
  
    
    
    

    public void RowApariencia(){
    
        tbDatos.setFocusable(false);
        //espacio entre comulnas
        tbDatos.setIntercellSpacing(new Dimension(0, 1));
        //altura de columnas 
        tbDatos.setRowHeight(25);
        //margen entre filas
        tbDatos.setRowMargin(0);
        //sin lineas verticles
        tbDatos.setShowVerticalLines(false);
        tbDatos.setSelectionBackground(new Color(97, 212, 195));
    }
    
    public void RowHeaderApariencia() {
        tbDatos.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 14));
        tbDatos.getTableHeader().setOpaque(false);
        tbDatos.getTableHeader().setBackground(new Color(97, 212, 195));
        tbDatos.getTableHeader().setForeground(new Color(255, 255, 255));

    
                    
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jl_atras = new javax.swing.JLabel();
        jt_category = new javax.swing.JTabbedPane();
        jp_database = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbmunicipio = new javax.swing.JComboBox<>();
        txtbuscar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        cmbestado = new javax.swing.JComboBox<>();

        jSeparator6.setBackground(new java.awt.Color(128, 128, 131));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 128, 131));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivocargosmall.png"))); // NOI18N
        jLabel8.setText("Modulo de Clientes");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 860, -1));

        jSeparator2.setBackground(new java.awt.Color(128, 128, 131));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1040, 10));

        jl_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left-arrow.png"))); // NOI18N
        jl_atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_atrasMouseClicked(evt);
            }
        });
        add(jl_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jp_database.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Estado");

        jLabel10.setText("Municipio");

        cmbmunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbmunicipioFocusLost(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        jLabel11.setText("BUSCAR");

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ESTADO", "MUNICIPIO", "COLONIA", "CP"
            }
        ));
        tbDatos.getTableHeader().setReorderingAllowed(false);
        tbDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        cmbestado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbestadoFocusLost(evt);
            }
        });
        cmbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbestadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_databaseLayout = new javax.swing.GroupLayout(jp_database);
        jp_database.setLayout(jp_databaseLayout);
        jp_databaseLayout.setHorizontalGroup(
            jp_databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_databaseLayout.createSequentialGroup()
                .addGroup(jp_databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_databaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jp_databaseLayout.createSequentialGroup()
                        .addGroup(jp_databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_databaseLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_databaseLayout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 257, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_databaseLayout.setVerticalGroup(
            jp_databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_databaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(68, 68, 68)
                .addGroup(jp_databaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jt_category.addTab("Consultar clientes", new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-list-filled.png")), jp_database); // NOI18N

        add(jt_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 880, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void jl_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_atrasMouseClicked
        Principal acceso = new Principal();
        new CambiaPanel(acceso.pnlPrincipal, new Vista.Pn_Pantalla_inicio());
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_atrasMouseClicked

    private void cmbmunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbmunicipioFocusLost

        cargar_colonias(cmbestado.getSelectedItem().toString(), cmbmunicipio.getSelectedItem().toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmunicipioFocusLost
DefaultTableModel dm;
    private void filtro(String consulta, JTable jtableBuscar) {
        dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }
    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        filtro(txtbuscar.getText().toUpperCase(), tbDatos);   // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void tbDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatosMouseClicked
     

        // TODO add your handling code here:
    }//GEN-LAST:event_tbDatosMouseClicked

    private void cmbestadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbestadoFocusLost
        cargar_municios(cmbestado.getSelectedItem().toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestadoFocusLost

    private void cmbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestadoActionPerformed

   
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbestado;
    private javax.swing.JComboBox<String> cmbmunicipio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jl_atras;
    private javax.swing.JPanel jp_database;
    private javax.swing.JTabbedPane jt_category;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
