/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
///
//para obtener posicion y uso de mouse en un elemento del jframe
import java.awt.MouseInfo;
import java.awt.Point;
/////////////
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
//clase que realiza los cambios entre paneles 
import Utilerias.CambiaPanel;
//utilerias necesaria para obtener el tamaño total de la pantalla y hacer 
//responsivo el sistema
import java.awt.Toolkit;
//necesario para extraer la hora y la fecha actuales
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame implements Runnable {

    String hora, minutos, segundos;
    Thread hilo;

    //variables para mover la pantalla sin tittle bar
    int x, y;

    /**
     * Creates new form Principal
     */

    public Principal() {
        setPantalla();
        initComponents();
        full_Screen();
        centrarPantalla();
        mostrarFecha();
        mostrarHora();
  cambiarapariencia("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        this.jb_home.setSelected(true);
        //necesario para hacer los cambios entre pantallas
        new CambiaPanel(pnlPrincipal, new Vista.Pn_Pantalla_inicio());
    }
void cambiarapariencia(String JOEL){
    try {
		UIManager.setLookAndFeel(JOEL);
	} catch (Exception e) {
		e.printStackTrace();
	}

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jb_home = new Utilerias.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jl_Icon_User = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jb_notas = new Utilerias.RSButtonMetro();
        jb_productos = new Utilerias.RSButtonMetro();
        jb_clientes = new Utilerias.RSButtonMetro();
        ocho = new Utilerias.RSButtonMetro();
        jb_acercade = new Utilerias.RSButtonMetro();
        jb_reportes = new Utilerias.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jb_menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_hora = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cerrar_sesion = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));
        pnlMenu.setVerifyInputWhenFocusTarget(false);

        jb_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        jb_home.setText("Principal");
        jb_home.setAutoscrolls(true);
        jb_home.setColorHover(new java.awt.Color(204, 204, 204));
        jb_home.setColorNormal(new java.awt.Color(204, 204, 204));
        jb_home.setColorPressed(new java.awt.Color(204, 204, 204));
        jb_home.setColorTextHover(new java.awt.Color(128, 128, 131));
        jb_home.setColorTextNormal(new java.awt.Color(128, 128, 131));
        jb_home.setColorTextPressed(new java.awt.Color(128, 128, 131));
        jb_home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jb_home.setIconTextGap(25);
        jb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jb_homeMousePressed(evt);
            }
        });
        jb_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_homeActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(239, 238, 244));

        jl_Icon_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save-the-children.png"))); // NOI18N
        jl_Icon_User.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("BIENVENIDO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Icon_User)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)))
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jl_Icon_User, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jb_notas.setBackground(new java.awt.Color(239, 238, 244));
        jb_notas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/stack-of-money.png"))); // NOI18N
        jb_notas.setText("     Notas");
        jb_notas.setColorHover(new java.awt.Color(204, 204, 204));
        jb_notas.setColorNormal(new java.awt.Color(239, 238, 244));
        jb_notas.setColorPressed(new java.awt.Color(204, 204, 204));
        jb_notas.setColorTextHover(new java.awt.Color(128, 128, 131));
        jb_notas.setColorTextNormal(new java.awt.Color(128, 128, 131));
        jb_notas.setColorTextPressed(new java.awt.Color(128, 128, 131));
        jb_notas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jb_notas.setIconTextGap(25);
        jb_notas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jb_notasMousePressed(evt);
            }
        });
        jb_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_notasActionPerformed(evt);
            }
        });

        jb_productos.setBackground(new java.awt.Color(239, 238, 244));
        jb_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cutlery.png"))); // NOI18N
        jb_productos.setText("  Productos");
        jb_productos.setColorHover(new java.awt.Color(204, 204, 204));
        jb_productos.setColorNormal(new java.awt.Color(239, 238, 244));
        jb_productos.setColorPressed(new java.awt.Color(204, 204, 204));
        jb_productos.setColorTextHover(new java.awt.Color(128, 128, 131));
        jb_productos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        jb_productos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        jb_productos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jb_productos.setIconTextGap(25);
        jb_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jb_productosMousePressed(evt);
            }
        });
        jb_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_productosActionPerformed(evt);
            }
        });

        jb_clientes.setBackground(new java.awt.Color(239, 238, 244));
        jb_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user-male.png"))); // NOI18N
        jb_clientes.setText("Clientes");
        jb_clientes.setColorHover(new java.awt.Color(204, 204, 204));
        jb_clientes.setColorNormal(new java.awt.Color(239, 238, 244));
        jb_clientes.setColorPressed(new java.awt.Color(204, 204, 204));
        jb_clientes.setColorTextHover(new java.awt.Color(128, 128, 131));
        jb_clientes.setColorTextNormal(new java.awt.Color(128, 128, 131));
        jb_clientes.setColorTextPressed(new java.awt.Color(128, 128, 131));
        jb_clientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jb_clientes.setIconTextGap(19);
        jb_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jb_clientesMousePressed(evt);
            }
        });
        jb_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clientesActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(239, 238, 244));
        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit-sign.png"))); // NOI18N
        ocho.setText("Cerrar Sesón");
        ocho.setColorHover(new java.awt.Color(204, 204, 204));
        ocho.setColorNormal(new java.awt.Color(239, 238, 244));
        ocho.setColorPressed(new java.awt.Color(204, 204, 204));
        ocho.setColorTextHover(new java.awt.Color(128, 128, 131));
        ocho.setColorTextNormal(new java.awt.Color(128, 128, 131));
        ocho.setColorTextPressed(new java.awt.Color(128, 128, 131));
        ocho.setHideActionText(true);
        ocho.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ocho.setIconTextGap(18);
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ochoMousePressed(evt);
            }
        });
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        jb_acercade.setBackground(new java.awt.Color(239, 238, 244));
        jb_acercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/info.png"))); // NOI18N
        jb_acercade.setText("Acerca de ");
        jb_acercade.setColorHover(new java.awt.Color(204, 204, 204));
        jb_acercade.setColorNormal(new java.awt.Color(239, 238, 244));
        jb_acercade.setColorPressed(new java.awt.Color(204, 204, 204));
        jb_acercade.setColorTextHover(new java.awt.Color(128, 128, 131));
        jb_acercade.setColorTextNormal(new java.awt.Color(128, 128, 131));
        jb_acercade.setColorTextPressed(new java.awt.Color(128, 128, 131));
        jb_acercade.setHideActionText(true);
        jb_acercade.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jb_acercade.setIconTextGap(25);
        jb_acercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jb_acercadeMousePressed(evt);
            }
        });
        jb_acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_acercadeActionPerformed(evt);
            }
        });

        jb_reportes.setBackground(new java.awt.Color(239, 238, 244));
        jb_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bullish.png"))); // NOI18N
        jb_reportes.setText("Reportes");
        jb_reportes.setColorHover(new java.awt.Color(204, 204, 204));
        jb_reportes.setColorNormal(new java.awt.Color(239, 238, 244));
        jb_reportes.setColorPressed(new java.awt.Color(204, 204, 204));
        jb_reportes.setColorTextHover(new java.awt.Color(128, 128, 131));
        jb_reportes.setColorTextNormal(new java.awt.Color(128, 128, 131));
        jb_reportes.setColorTextPressed(new java.awt.Color(128, 128, 131));
        jb_reportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jb_reportes.setIconTextGap(19);
        jb_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jb_reportesMousePressed(evt);
            }
        });
        jb_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jb_home, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jb_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jb_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jb_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jb_acercade, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jb_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jb_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jb_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jb_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jb_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jb_acercade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jb_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jb_menu.setBorder(null);
        jb_menu.setContentAreaFilled(false);
        jb_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_menuActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Principal");

        lb_fecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lb_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lb_fecha.setText("dd/mm/yy");

        lb_hora.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lb_hora.setForeground(new java.awt.Color(255, 255, 255));
        lb_hora.setText("00:00:00");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora actual");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha Actual");

        cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder_close16_216470.png"))); // NOI18N
        cerrar_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_sesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_menu)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 573, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar_sesion)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrar_sesion)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_hora)
                            .addComponent(lb_fecha)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addComponent(jb_menu)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        jPanel9.setBackground(new java.awt.Color(239, 238, 244));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel11.setText("Sistema de Notas FESTUM");

        jLabel12.setBackground(new java.awt.Color(103, 206, 210));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Luis Tobon Hernandez");

        jLabel13.setBackground(new java.awt.Color(103, 206, 210));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("USUARIO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPantalla() {

        //para eliminar el tittle bar
        this.setUndecorated(true);
        //para que no le cambien el tamaño
        this.setResizable(false);

    }

    public void centrarPantalla() {
        //para dejar el menu centrado y estatico
        this.setLocationRelativeTo(null);

    }

    public void full_Screen() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);

    }

    public static String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    public void hora() {
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);

    }

    public void run() {
        // Thread current= Thread.currentThread();
        for (int i = 1; i > 0; i++) {
            if (i > 0) {
                hora();
                lb_hora.setText(hora + ":" + minutos + ":" + segundos);
            }
        }
    }

    public void mostrarFecha() {
        //componente para fecha
        lb_fecha.setText(fecha());
    }

    public void mostrarHora() {
        //componentes para la hora
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
    }

    private void jb_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_homeActionPerformed
        new CambiaPanel(pnlPrincipal, new Vista.Pn_Pantalla_inicio());
        if (this.jb_home.isSelected()) {
            this.jb_home.setColorNormal(new Color(239, 238, 244));
            this.jb_home.setColorHover(new Color(103,206,210));
            this.jb_home.setColorPressed(new Color(103,206,210));

            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));

            this.jb_notas.setColorNormal(new Color(239, 238, 244));
            this.jb_notas.setColorHover(new Color(103,206,210));
            this.jb_notas.setColorPressed(new Color(103,206,210));

            this.jb_reportes.setColorNormal(new Color(239, 238, 244));
            this.jb_reportes.setColorHover(new Color(103,206,210));
            this.jb_reportes.setColorPressed(new Color(103,206,210));

            this.jb_clientes.setColorNormal(new Color(239, 238, 244));
            this.jb_clientes.setColorHover(new Color(103,206,210));
            this.jb_clientes.setColorPressed(new Color(103,206,210));

        

            this.jb_acercade.setColorNormal(new Color(239, 238, 244));
            this.jb_acercade.setColorHover(new Color(103,206,210));
            this.jb_acercade.setColorPressed(new Color(103,206,210));

            this.ocho.setColorNormal(new Color(239, 238, 244));
            this.ocho.setColorHover(new Color(103,206,210));
            this.ocho.setColorPressed(new Color(103,206,210));
        } else {
            this.jb_home.setColorNormal(new Color(239, 238, 244));
            this.jb_home.setColorHover(new Color(103,206,210));
            this.jb_home.setColorPressed(new Color(103,206,210));
        }
    }//GEN-LAST:event_jb_homeActionPerformed

    private void jb_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_homeMousePressed
        this.jb_home.setSelected(true);
        this.jb_productos.setSelected(false);
        this.jb_notas.setSelected(false);
        this.jb_reportes.setSelected(false);
        this.jb_clientes.setSelected(false);

        this.jb_acercade.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_jb_homeMousePressed

    private void jb_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_notasActionPerformed
  new CambiaPanel(pnlPrincipal, new Vista.Pn_Menu_Notas());
        if (this.jb_notas.isSelected()) {
            this.jb_home.setColorNormal(new Color(239,238, 244));
            this.jb_home.setColorHover(new Color(103,206,210));
            this.jb_home.setColorPressed(new Color(103,206,210));
//color de boton al ser seleccionado 
            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));

           this.jb_notas.setColorNormal(new Color(204, 204, 204));
            this.jb_notas.setColorHover(new Color(103,206,210));
            this.jb_notas.setColorPressed(new Color(103,206,210));

            this.jb_reportes.setColorNormal(new Color(239, 238, 244));
            this.jb_reportes.setColorHover(new Color(103,206,210));
            this.jb_reportes.setColorPressed(new Color(103,206,210));

            this.jb_clientes.setColorNormal(new Color(239, 238, 244));
            this.jb_clientes.setColorHover(new Color(103,206,210));
            this.jb_clientes.setColorPressed(new Color(103,206,210));

        

            this.jb_acercade.setColorNormal(new Color(239, 238, 244));
            this.jb_acercade.setColorHover(new Color(103,206,210));
            this.jb_acercade.setColorPressed(new Color(103,206,210));

            this.ocho.setColorNormal(new Color(239, 238, 244));
            this.ocho.setColorHover(new Color(103,206,210));
            this.ocho.setColorPressed(new Color(103,206,210));
        } else {
            //color del boton cuando no esta seleccionado
            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));
        }
    }//GEN-LAST:event_jb_notasActionPerformed

    private void jb_notasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_notasMousePressed
this.jb_home.setSelected(false);
        this.jb_productos.setSelected(false);
        this.jb_notas.setSelected(true);
        this.jb_reportes.setSelected(false);
        this.jb_clientes.setSelected(false);
        
        this.jb_acercade.setSelected(false);
        this.ocho.setSelected(false);
        
        
        
        
    }//GEN-LAST:event_jb_notasMousePressed

    private void jb_productosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_productosMousePressed
        this.jb_home.setSelected(false);
        this.jb_productos.setSelected(true);
        this.jb_notas.setSelected(false);
        this.jb_reportes.setSelected(false);
        this.jb_clientes.setSelected(false);
        this.jb_acercade.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_jb_productosMousePressed

    private void jb_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_productosActionPerformed
        new CambiaPanel(pnlPrincipal, new Vista.Pn_Menu_Productos());
        if (this.jb_productos.isSelected()) {
            this.jb_home.setColorNormal(new Color(239,238, 244));
            this.jb_home.setColorHover(new Color(103,206,210));
            this.jb_home.setColorPressed(new Color(103,206,210));
//color de boton al ser seleccionado 
            this.jb_productos.setColorNormal(new Color(204, 204, 204));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));

            this.jb_notas.setColorNormal(new Color(239, 238, 244));
            this.jb_notas.setColorHover(new Color(103,206,210));
            this.jb_notas.setColorPressed(new Color(103,206,210));

            this.jb_reportes.setColorNormal(new Color(239, 238, 244));
            this.jb_reportes.setColorHover(new Color(103,206,210));
            this.jb_reportes.setColorPressed(new Color(103,206,210));

            this.jb_clientes.setColorNormal(new Color(239, 238, 244));
            this.jb_clientes.setColorHover(new Color(103,206,210));
            this.jb_clientes.setColorPressed(new Color(103,206,210));

           
            this.jb_acercade.setColorNormal(new Color(239, 238, 244));
            this.jb_acercade.setColorHover(new Color(103,206,210));
            this.jb_acercade.setColorPressed(new Color(103,206,210));

            this.ocho.setColorNormal(new Color(239, 238, 244));
            this.ocho.setColorHover(new Color(103,206,210));
            this.ocho.setColorPressed(new Color(103,206,210));
        } else {
            //color del boton cuando no esta seleccionado
            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));
        }

    }//GEN-LAST:event_jb_productosActionPerformed

    private void jb_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_menuActionPerformed

        // FUNCION NO DISPONIBLE AUN //
        /* int posicion = pnlMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
     }*/
    }//GEN-LAST:event_jb_menuActionPerformed

    private void ochoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMousePressed

    }//GEN-LAST:event_ochoMousePressed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed

    }//GEN-LAST:event_ochoActionPerformed

    private void jb_acercadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_acercadeMousePressed
        this.jb_home.setSelected(false);
        this.jb_productos.setSelected(false);
        this.jb_notas.setSelected(false);
        this.jb_reportes.setSelected(false);
        this.jb_clientes.setSelected(false);
              this.jb_acercade.setSelected(true);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_jb_acercadeMousePressed

    private void jb_acercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_acercadeActionPerformed
        new CambiaPanel(pnlPrincipal, new Vista.Pn_Acercade());
        if (this.jb_acercade.isSelected()) {
            this.jb_home.setColorNormal(new Color(239, 238, 244));
            this.jb_home.setColorHover(new Color(204, 204, 204));
            this.jb_home.setColorPressed(new Color(204, 204, 204));

            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(204, 204, 204));
            this.jb_productos.setColorPressed(new Color(204, 204, 204));

            this.jb_notas.setColorNormal(new Color(239, 238, 244));
            this.jb_notas.setColorHover(new Color(204, 204, 204));
            this.jb_notas.setColorPressed(new Color(204, 204, 204));

            this.jb_reportes.setColorNormal(new Color(239, 238, 244));
            this.jb_reportes.setColorHover(new Color(204, 204, 204));
            this.jb_reportes.setColorPressed(new Color(204, 204, 204));

            this.jb_clientes.setColorNormal(new Color(239, 238, 244));
            this.jb_clientes.setColorHover(new Color(204, 204, 204));
            this.jb_clientes.setColorPressed(new Color(204, 204, 204));

       
          this.jb_productos.setColorNormal(new Color(204, 204, 204));
            this.jb_acercade.setColorHover(new Color(204, 204, 204));
            this.jb_acercade.setColorPressed(new Color(204, 204, 204));

            this.ocho.setColorNormal(new Color(239, 238, 244));
            this.ocho.setColorHover(new Color(204, 204, 204));
            this.ocho.setColorPressed(new Color(204, 204, 204));
        } else {
            this.jb_acercade.setColorNormal(new Color(239, 238, 244));
            this.jb_acercade.setColorHover(new Color(204, 204, 204));
            this.jb_acercade.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jb_acercadeActionPerformed

    private void jb_reportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_reportesMousePressed
this.jb_home.setSelected(false);
        this.jb_productos.setSelected(false);
        this.jb_notas.setSelected(false);
        this.jb_reportes.setSelected(true);
        this.jb_clientes.setSelected(false);
        
        this.jb_acercade.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_jb_reportesMousePressed

    private void jb_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reportesActionPerformed
        new CambiaPanel(pnlPrincipal, new Vista.Pn_Menu_REPORTES());
        if (this.jb_reportes.isSelected()) {
            this.jb_home.setColorNormal(new Color(239,238, 244));
            this.jb_home.setColorHover(new Color(103,206,210));
            this.jb_home.setColorPressed(new Color(103,206,210));
//color de boton al ser seleccionado 
            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));

            this.jb_notas.setColorNormal(new Color(239, 238, 244));
            this.jb_notas.setColorHover(new Color(103,206,210));
            this.jb_notas.setColorPressed(new Color(103,206,210));

            this.jb_reportes.setColorNormal(new Color(204, 204, 204));
            this.jb_reportes.setColorHover(new Color(103,206,210));
            this.jb_reportes.setColorPressed(new Color(103,206,210));

            this.jb_clientes.setColorNormal(new Color(239, 238, 244));
            this.jb_clientes.setColorHover(new Color(103,206,210));
            this.jb_clientes.setColorPressed(new Color(103,206,210));

           
            this.jb_acercade.setColorNormal(new Color(239, 238, 244));
            this.jb_acercade.setColorHover(new Color(103,206,210));
            this.jb_acercade.setColorPressed(new Color(103,206,210));

            this.ocho.setColorNormal(new Color(239, 238, 244));
            this.ocho.setColorHover(new Color(103,206,210));
            this.ocho.setColorPressed(new Color(103,206,210));
        } else {
            //color del boton cuando no esta seleccionado
            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));
        }

    }//GEN-LAST:event_jb_reportesActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       //funcionalidad no necesario aun
        // x = evt.getX();
        //y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

//FUNCION NO NECESARIA AUN
//        Point mueve = MouseInfo.getPointerInfo().getLocation();
  //      this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void cerrar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_sesionMouseClicked
        System.exit(0);   //cierra el sistema
    }//GEN-LAST:event_cerrar_sesionMouseClicked

    private void jb_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clientesActionPerformed
      new CambiaPanel(pnlPrincipal, new Vista.Pn_Menu_Clientes());
        if (this.jb_clientes.isSelected()) {
            this.jb_home.setColorNormal(new Color(239,238, 244));
            this.jb_home.setColorHover(new Color(103,206,210));
            this.jb_home.setColorPressed(new Color(103,206,210));
//color de boton al ser seleccionado 
            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));

            this.jb_notas.setColorNormal(new Color(239, 238, 244));
            this.jb_notas.setColorHover(new Color(103,206,210));
            this.jb_notas.setColorPressed(new Color(103,206,210));

            this.jb_reportes.setColorNormal(new Color(239, 238, 244));
            this.jb_reportes.setColorHover(new Color(103,206,210));
            this.jb_reportes.setColorPressed(new Color(103,206,210));

            this.jb_clientes.setColorNormal(new Color(204, 204, 204));
            this.jb_clientes.setColorHover(new Color(103,206,210));
            this.jb_clientes.setColorPressed(new Color(103,206,210));

           
            this.jb_acercade.setColorNormal(new Color(239, 238, 244));
            this.jb_acercade.setColorHover(new Color(103,206,210));
            this.jb_acercade.setColorPressed(new Color(103,206,210));

            this.ocho.setColorNormal(new Color(239, 238, 244));
            this.ocho.setColorHover(new Color(103,206,210));
            this.ocho.setColorPressed(new Color(103,206,210));
        } else {
            //color del boton cuando no esta seleccionado
            this.jb_productos.setColorNormal(new Color(239, 238, 244));
            this.jb_productos.setColorHover(new Color(103,206,210));
            this.jb_productos.setColorPressed(new Color(103,206,210));
        }
    }//GEN-LAST:event_jb_clientesActionPerformed

    private void jb_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clientesMousePressed
   this.jb_home.setSelected(false);
        this.jb_productos.setSelected(false);
        this.jb_notas.setSelected(false);
        this.jb_reportes.setSelected(false);
        this.jb_clientes.setSelected(true);
        this.jb_acercade.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_jb_clientesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrar_sesion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Utilerias.RSButtonMetro jb_acercade;
    private Utilerias.RSButtonMetro jb_clientes;
    private Utilerias.RSButtonMetro jb_home;
    private javax.swing.JButton jb_menu;
    private Utilerias.RSButtonMetro jb_notas;
    private Utilerias.RSButtonMetro jb_productos;
    private Utilerias.RSButtonMetro jb_reportes;
    private javax.swing.JLabel jl_Icon_User;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_hora;
    private Utilerias.RSButtonMetro ocho;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    public javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
